#' UI Module for Data Upload in Shiny
#'
#' @description
#' This function creates a Shiny UI module for uploading data files from Runsalt output.
#'
#'
#' @param id A character string that defines the namespace for the module's UI elements.
#'
#' @returns A `tagList` containing a `uiOutput` for file upload.
#' @export
#'
#' @import shiny
#'
#' @examples
#' \dontrun{
#' ui <- fluidPage(
#'   shiny_dataUploadUI("dataUpload")
#' )
#' }
#'
shiny_dataUploadUI <- function(id) {
  ns <- NS(id)
  tagList(
    # File input UI generated by the server
    uiOutput(ns("file_upload")),

    # Data table output to display the tidied data
    DT::dataTableOutput(ns("tidied_table"))
  )
}
